services:
  postgres:
    image: postgres:16-alpine
    container_name: rachaconta-db
    environment:
      POSTGRES_DB: rachacontaapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev2026
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: